<?php
declare(strict_types=1);
// Rebuilds database/install.sql (schema + seeds in one file) for importing through phpMyAdmin.
$db = $argv[1] ?? 'circular_economy';
$out = "-- EcoZin one-file installer (generated by database/build-install-sql.php — do not edit by hand)\n"
     . "-- phpMyAdmin: Import this file. It creates the `$db` database if it does not exist.\n"
     . "CREATE DATABASE IF NOT EXISTS `$db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\nUSE `$db`;\n\n"
     . file_get_contents(__DIR__ . '/schema.sql') . "\n" . file_get_contents(__DIR__ . '/seeds.sql');
file_put_contents(__DIR__ . '/install.sql', $out);
echo "wrote database/install.sql (" . strlen($out) . " bytes)\n";
